services:
  infra:
    build:
      context: ./infra
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: cdk
    working_dir: /workspace/infra
    volumes:
      - ./infra:/workspace/infra
      - ~/.aws:/home/node/.aws
    command: sleep infinity
    tty: true
    stdin_open: true
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: go
    working_dir: /workspace/backend
    volumes:
      - ./backend:/workspace/backend
      - ~/.aws:/home/appuser/.aws
      - /workspace/backend/pkg
      - /workspace/backend/bin
    ports:
      - "8080:8080"
    environment:
      - INPUT_BUCKET_NAME=${INPUT_BUCKET_NAME}
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: typescript
    working_dir: /workspace/frontend
    volumes:
      - ./frontend:/workspace/frontend
      - frontend_node_modules:/workspace/frontend/node_modules
      - ./.git:/workspace/.git:ro
    ports:
      - "8081:5173"
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    networks:
      - app-network

    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules:
