services:
  infra:
    build:
      context: ./infra
    container_name: cdk
    working_dir: /workspace/infra
    volumes:
      - .:/workspace
      - ~/.aws:/home/node/.aws
    command: sleep infinity
    tty: true
    stdin_open: true

  backend:
    build:
      context: ./backend
      target: dev
    container_name: go
    volumes:
      - ./backend:/app
      - ~/.aws:/root/.aws:ro
    ports:
      - "8080:8080"
    environment:
      - INPUT_BUCKET_NAME=${INPUT_BUCKET_NAME}
