#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = "tmp" 

[build]
  cmd = """
    if [ "$IS_LAMBDA" = "true" ]; then \
      GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags lambda.norpc -trimpath -ldflags="-s -w" -o bin/presign/bootstrap ./cmd/presign/main.go; \
    else \
      go run ./cmd/presign/main.go; \
    fi
  """
  delay = 1000
  exclude_dir = ["bin", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  stop_on_error = false
  log = "build-errors.log"
  poll = true
  poll_interval = 500

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
