name: Infra CI

on:
  pull_request:
    paths:
      - 'infra/**'
      - '.github/workflows/infra-cd-dev.yml'
      - '.github/workflows/infra-ci.yml'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.3'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::626635405187:role/jpeg-to-json-cicd-role
          aws-region: ap-northeast-1

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: CDK Synth
        run: npx cdk synth

      - name: CDK Diff
        run: npx cdk diff
